# Generated by Django 3.2.9 on 2021-12-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='password',
            field=models.CharField(default='nulo', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(default='nulo', max_length=40),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(default='nulo', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default='nulo', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default='nulo', max_length=12),
        ),
    ]
